services:
  sfcm-db:
    container_name: sfcm-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    restart: always
    networks:
      - sfcm-net
    environment:
      - MSSQL_SA_PASSWORD=100%Point
      - ACCEPT_EULA=Y
      - DB_NAME=SFCM
    volumes:
      - sfcm-db:/var/opt/mssql

networks:
  sfcm-net:
    name: sfcm-net

volumes:
  sfcm-db:
    name: sfcm-db