version: "3.8"

services:
  sfcm:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 2024:2024
        #    volumes:
        #      - /root/gtos-backend:/app
    restart: always


